// PTSD Pipeline Plugin for OpenCode
// Generated by ptsd init -- do not edit manually

import { definePlugin } from "opencode/plugin";

export default definePlugin({
  name: "ptsd",
  hooks: {
    "session.start": async (ctx) => {
      const result = await ctx.exec("{{.Bin}} context --agent");
      return { message: result.stdout };
    },
    "tool.execute.before": async (ctx, event) => {
      if (event.tool !== "write" && event.tool !== "edit") return;
      const filePath = event.input?.file_path || event.input?.path || "";
      if (!filePath) return;
      const result = await ctx.exec(
        `{{.Bin}} gate-check --file "${filePath}" --agent`
      );
      if (result.exitCode !== 0) {
        return { blocked: true, message: result.stderr };
      }
    },
    "tool.execute.after": async (ctx, event) => {
      if (event.tool !== "write" && event.tool !== "edit") return;
      const filePath = event.input?.file_path || event.input?.path || "";
      if (!filePath) return;
      await ctx.exec(
        `echo '{"tool_input":{"file_path":"${filePath}"}}' | {{.Bin}} hooks post-tool-use --agent`
      );
    },
  },
});
